version: '3.7'
services:
  api_service:
    build: .
    restart: always
    ports:
      - 9090:8080
    environment:
      URLHOST: postgres_db_book
      DB_NAME: book_db
      USERNAME: postgres
      PASSWORD: 123456
    depends_on:
      - postgres_db_book
  postgres_db_book:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: book_db