version: '3.7'
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      URLHOST: ${HOST_NAME_DB}
      USERNAME: ${USERNAME_DB}
      PASSWORD: ${PASSWORD_DB}
    depends_on:
      - postgres_db_book
  postgres_db_book:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_DB: book_db