spring:
  datasource:
#    url: jdbc:postgresql://postgres_db_book:5432/book_db
    url: jdbc:postgresql://${URLHOST}:${PORTDB}/${PGDATABASE}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
server:
  error:
    include-message: always
#  port: 9090

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG

pringdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

