spring:
  datasource:
    url: jdbc:postgresql://postgres_db_book:5432/book_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
server:
  error:
    include-message: always

